In [84]:
# Import Dependencies and Setup
import pandas as pd
import csv
import os

# Files to Load
museum1_path = os.path.join(os.getcwd(), "Raw_Data", "MuseumFile2018_File1_Nulls.csv")
museum2_path = os.path.join(os.getcwd(), "Raw_Data", "MuseumFile2018_File2_Nulls.csv")
museum3_path = os.path.join(os.getcwd(), "Raw_Data", "MuseumFile2018_File3_Nulls.csv")
# museums_path = os.path.join(os.getcwd(), "Raw_Data", "museums_separated.csv")
# trip_path = os.path.join(os.getcwd(), "Raw_Data", "tripadvisor_merged.csv")
trip1_path = os.path.join(os.getcwd(), "Raw_Data", "tripadvisor_museum_USonly.csv")
# trip2_path = os.path.join(os.getcwd(), "Raw_Data", "tripadvisor_museum_world.csv")

In [85]:
# Read Files and Store Into Pandas Data Frame
museum1_df = pd.read_csv(museum1_path, encoding= 'unicode_escape')
museum2_df = pd.read_csv(museum2_path, encoding= 'unicode_escape')
museum3_df = pd.read_csv(museum3_path, encoding= 'unicode_escape')
# trip_df = pd.read_csv(trip_path)
trip1_df = pd.read_csv(trip1_path)
# trip2_df = pd.read_csv(trip2_path)

In [86]:
museum1_df.head()

,DISCIPL,COMMONNAME,LEGALNAME,ADSTREET,ADSTATE,ADZIP5,PHONE,WEBURL,REVENUE15,LONGITUDE,LATITUDE,GSTREET
0,ART,MOBILE MUSEUM OF ART,THE MOBILE MUSEUM OF ART INC,4850 MUSEUM DR,AL,36689,2512085200,HTTP://WWW.MOBILEMUSEUMOFART.COM/,3668329,-88.15462,30.70401,4850 MUSEUM DR
1,ART,MONTGOMERY MUSEUM OF FINE ARTS,MONTGOMERY MUSEUM OF FINE ARTS ASSOCIATION,ONE MUSEUM DRIVE,AL,36123,3342404333,HTTP://MMFA.ORG/,2759203,-86.2087,32.3526,ONE MUSEUM DRIVE
2,HST,HISTORY MUSEUM OF MOBILE,MOBILE MEDICAL MUSEUM INC,111 SOUTH ROYAL STREET,AL,36602,2512087569,,20453,-88.07704,30.69234,1664 SPRING HILL AVE
3,BOT,JASMINE HILL GARDENS AND OUTDOOR MUSEUM,JASMINE HILL GARDENS AND OUTDOOR MUSEUM,3001 JASMINE HILL RD,AL,36093,3342635713,HTTP://WWW.JASMINEHILL.ORG,,-86.1874,32.49562,3001 JASMINE HILL RD
4,ART,JAN DEMPSEY ARTS CENTER,JAN DEMPSEY ARTS CENTER,222 E DRAKE AVE,AL,36830,3345012963,,,-85.4782,32.61408,222 E DRAKE AVE

In [87]:
## Rename DISCIPL to DISCIPLINE
museum1_df = museum1_df.rename(columns={"DISCIPL" : "DISCIPLINE" })
museum1_df.head()

,DISCIPLINE,COMMONNAME,LEGALNAME,ADSTREET,ADSTATE,ADZIP5,PHONE,WEBURL,REVENUE15,LONGITUDE,LATITUDE,GSTREET
0,ART,MOBILE MUSEUM OF ART,THE MOBILE MUSEUM OF ART INC,4850 MUSEUM DR,AL,36689,2512085200,HTTP://WWW.MOBILEMUSEUMOFART.COM/,3668329,-88.15462,30.70401,4850 MUSEUM DR
1,ART,MONTGOMERY MUSEUM OF FINE ARTS,MONTGOMERY MUSEUM OF FINE ARTS ASSOCIATION,ONE MUSEUM DRIVE,AL,36123,3342404333,HTTP://MMFA.ORG/,2759203,-86.2087,32.3526,ONE MUSEUM DRIVE
2,HST,HISTORY MUSEUM OF MOBILE,MOBILE MEDICAL MUSEUM INC,111 SOUTH ROYAL STREET,AL,36602,2512087569,,20453,-88.07704,30.69234,1664 SPRING HILL AVE
3,BOT,JASMINE HILL GARDENS AND OUTDOOR MUSEUM,JASMINE HILL GARDENS AND OUTDOOR MUSEUM,3001 JASMINE HILL RD,AL,36093,3342635713,HTTP://WWW.JASMINEHILL.ORG,,-86.1874,32.49562,3001 JASMINE HILL RD
4,ART,JAN DEMPSEY ARTS CENTER,JAN DEMPSEY ARTS CENTER,222 E DRAKE AVE,AL,36830,3345012963,,,-85.4782,32.61408,222 E DRAKE AVE

In [88]:
museum1_df.count()

DISCIPLINE    7431
COMMONNAME    7431
LEGALNAME     7431
ADSTREET      7431
ADSTATE       7431
ADZIP5        7431
PHONE         7431
WEBURL        7431
REVENUE15     7431
LONGITUDE     7431
LATITUDE      7431
GSTREET       7430
dtype: int64

In [89]:
museum2_df.head()

,DISCIPLINE,COMMONNAME,LEGALNAME,ADSTREET,ADSTATE,ADZIP5,PHONE,WEBURL,REVENUE15,LONGITUDE,LATITUDE,GSTREET
0,GMU,WESTERVELT-WARNER MUSEUM OF AMERICAN ART,WESTERVELT WARNER MUSEUM,8316 MOUNTBATTEN RD NE,AL,35406,2055625280,HTTP://TUSCALOOSAMOA.ORG/,,-87.5051,33.29531,8316 MOUNTBATTEN RD NE
1,GMU,U. S. ARMY AVIATION MUSEUM,ARMY AVIATION MUSEUM FOUNDATION INC,6000 NOVOSEL ST,AL,36362,3345982508,,256287,-85.71978,31.34936,PO BOX 620610
2,GMU,U.S. SPACE & ROCKET CENTER,U.S. SPACE & ROCKET CENTER FOUNDATION,ONE TRANQUILITY BASE,AL,35807,2568373400,HTTP://ROCKETCENTER.COM/,2022595,-86.62841,34.7138,ONE TRANQUILITY BASE
3,GMU,WELLBORN MUSCLECAR MUSEUM,WELLBORN MUSCLECAR MUSEUM,124 BROAD ST,AL,35010,2563298474,HTTP://WELLBORNMUSCLECARMUSEUM.COM,,-85.95541,32.94394,124 BROAD ST
4,GMU,USS ALABAMA BATTLESHIP,USS ALABAMA BATTLESHIP COMMISSION,2703 BATTLESHIP PKWY,AL,36527,2514332703,HTTP://WWW.USSALABAMA.COM,,-88.04483,30.69095,2703 BATTLESHIP PKWY

In [90]:
museum2_df.count()

DISCIPLINE    7961
COMMONNAME    7961
LEGALNAME     7961
ADSTREET      7961
ADSTATE       7961
ADZIP5        7961
PHONE         7961
WEBURL        7961
REVENUE15     7961
LONGITUDE     7961
LATITUDE      7961
GSTREET       7961
dtype: int64

In [91]:
museum3_df.head()

,DISCIPLINE,COMMONNAME,LEGALNAME,ADSTREET,ADSTATE,ADZIP5,PHONE,WEBURL,REVENUE15,LONGITUDE,LATITUDE,GSTREET
0,,,,,,,,,,,,
1,HSC,STURDIVANT HALL,STURDIVANT MUSEUM ASSOCIATION OF SELMA INC,713 MABRY ST,AL,36702,3348725626,,291156,-87.02243,32.40623,PO BOX 1205
2,HSC,SLOSS FURNACES NATIONAL HISTORIC LANDMARK,SLOSS FURNACES FOUNDATION INC,20 32ND ST N,AL,35222,2053241911,HTTP://SLOSSFURNACES.COM/,375106,-86.78855,33.52109,20 32ND ST N
3,HSC,NORTHPORT HERITAGE MUSEUM,FRIENDS OF HISTORIC NORTHPORT INC,1991 PARK ST,AL,35476,2055238720,HTTP://NORTHPORT-SMITHSONIAN.ORG/,0,-87.58354,33.23036,PO BOX 393
4,HSC,ORDEMAN-SHAW HOUSE,ORDEMAN-SHAW HOUSE,310 N HULL ST,AL,36104,3106485578,,,-86.30384,32.38171,310 N HULL ST

In [92]:
museum3_df.count()

DISCIPLINE    14786
COMMONNAME    14786
LEGALNAME     14786
ADSTREET      14786
ADSTATE       14786
ADZIP5        14786
PHONE         14786
WEBURL        14786
REVENUE15     14786
LONGITUDE     14786
LATITUDE      14786
GSTREET       14786
dtype: int64

In [123]:
## Combine the data into a single dataset
merged_df = pd.merge(museum1_df, museum2_df, how="left")
merged_df

,DISCIPLINE,COMMONNAME,LEGALNAME,ADSTREET,ADSTATE,ADZIP5,PHONE,WEBURL,REVENUE15,LONGITUDE,LATITUDE,GSTREET
0,ART,MOBILE MUSEUM OF ART,THE MOBILE MUSEUM OF ART INC,4850 MUSEUM DR,AL,36689,2512085200,HTTP://WWW.MOBILEMUSEUMOFART.COM/,3668329,-88.15462,30.70401,4850 MUSEUM DR
1,ART,MONTGOMERY MUSEUM OF FINE ARTS,MONTGOMERY MUSEUM OF FINE ARTS ASSOCIATION,ONE MUSEUM DRIVE,AL,36123,3342404333,HTTP://MMFA.ORG/,2759203,-86.2087,32.3526,ONE MUSEUM DRIVE
2,HST,HISTORY MUSEUM OF MOBILE,MOBILE MEDICAL MUSEUM INC,111 SOUTH ROYAL STREET,AL,36602,2512087569,,20453,-88.07704,30.69234,1664 SPRING HILL AVE
3,BOT,JASMINE HILL GARDENS AND OUTDOOR MUSEUM,JASMINE HILL GARDENS AND OUTDOOR MUSEUM,3001 JASMINE HILL RD,AL,36093,3342635713,HTTP://WWW.JASMINEHILL.ORG,,-86.1874,32.49562,3001 JASMINE HILL RD
4,ART,JAN DEMPSEY ARTS CENTER,JAN DEMPSEY ARTS CENTER,222 E DRAKE AVE,AL,36830,3345012963,,,-85.4782,32.61408,222 E DRAKE AVE
...,...,...,...,...,...,...,...,...,...,...,...,...
7426,ART,YORK COLLEGE GALLERIES,YORK COLLEGE OF PENNSYLVANIA,441 COUNTRY CLUB RD,PA,17403,7178156622,,123299897,-76.7091,39.94357,COUNTRY CLUB ROAD
7427,ART,YOST ART GALLERY,YOST ART GALLERY,606 W MAIN,KS,66035,,,,-95.27101,39.85962,606 W MAIN
7428,ART,ZIMMERLI ART MUSEUM,RUTGERS THE STATE UNIVERSITY OF NJ,71 HAMILTON STREET,NJ,8901,7329327237,HTTP://WWW.ZIMMERLIMUSEUM.RUTGERS.EDU,,-74.45727,40.5253,65 DAVIDSON RD - RM 317
7429,ART,ZOLLER GALLERY,ZOLLER GALLERY,201 OLD MAIN,PA,16802,,,,-77.86267,40.79792,201 OLD MAIN
7430,ART,ZUCKERMAN MUSEUM OF ART,ZUCKERMAN MUSEUM OF ART,492 PRILLAMAN WA,GA,30144,,HTTP://ZUCKERMAN.KENNESAW.EDU/,,-84.56889,34.0372,492 PRILLAMAN WA

In [127]:
## Combine the merged df with final museum df into a single dataset
merged_museum_df = pd.merge(museum3_df.astype(str), merged_df.astype(str), how="left")
merged_museum_df

,DISCIPLINE,COMMONNAME,LEGALNAME,ADSTREET,ADSTATE,ADZIP5,PHONE,WEBURL,REVENUE15,LONGITUDE,LATITUDE,GSTREET
0,,,,,,,,,,,,
1,HSC,STURDIVANT HALL,STURDIVANT MUSEUM ASSOCIATION OF SELMA INC,713 MABRY ST,AL,36702,3348725626,,291156,-87.02243,32.40623,PO BOX 1205
2,HSC,SLOSS FURNACES NATIONAL HISTORIC LANDMARK,SLOSS FURNACES FOUNDATION INC,20 32ND ST N,AL,35222,2053241911,HTTP://SLOSSFURNACES.COM/,375106,-86.78855,33.52109,20 32ND ST N
3,HSC,NORTHPORT HERITAGE MUSEUM,FRIENDS OF HISTORIC NORTHPORT INC,1991 PARK ST,AL,35476,2055238720,HTTP://NORTHPORT-SMITHSONIAN.ORG/,0,-87.58354,33.23036,PO BOX 393
4,HSC,ORDEMAN-SHAW HOUSE,ORDEMAN-SHAW HOUSE,310 N HULL ST,AL,36104,3106485578,,,-86.30384,32.38171,310 N HULL ST
...,...,...,...,...,...,...,...,...,...,...,...,...
14781,HSC,TRYON PALACE HISTORIC SITES & GARDENS KYNA HER...,TRYON PALACE HISTORIC SITES & GARDENS KYNA HER...,PO BOX 1007,NC,28563,2526393500,HTTP://WWW.TRYONPALACE.ORG,,-77.04021,35.10562,PO BOX 1007
14782,HSC,WESTMORELAND CTY HISTORICAL SOCIETY,WESTMORELAND CTY HISTORICAL SOCIETY,362 SAND HILL RD SUITE 1,PA,15601,7245321935,HTTP://WWW.WESTMORELANDHISTORY.ORG,,-79.43842,40.28467,362 SAND HILL RD SUITE 1
14783,HSC,WISCONSIN HISTORICAL SOCIETY ACQUISITIONS,WISCONSIN HISTORICAL SOCIETY ACQUISITIONS,SECTION 816 STATE STREET,WI,53706,6082646598,HTTP://WWW.WISCONSINHISTORY.ORG/CONTENT.ASPX?D...,,-89.41425,43.073,SECTION 816 STATE STREET
14784,HSC,BARTOW-PELL MANSION MUSEUM AND GARDENS,BARTOW-PELL MANSION MUSEUM AND GARDENS,895 SHORE ROAD,NY,10464,,HTTP://WWW.BARTOWPELLMANSIONMUSEUM.ORG/,,-73.79448,40.88292,895 SHORE ROAD
14785,HSC,ROOSEVELT VANDERBILT NATIONAL HISTORIC SITE,ROOSEVELT VANDERBILT NATIONAL HISTORIC SITE,4097 ALBANY POST RD,NY,12538,,HTTP://WWW.NPS.GOV/HOFR/ROOSEVELT-VANDERBILT-N...,,-73.91055,41.76829,4097 ALBANY POST RD

In [128]:
merged_museum_df.to_csv(r'c:\\Users\\vaab2\OneDrive\\Desktop\\Excercises in class\\Project-MAZE\\Valense\\Raw_Data\\museums_final.csv', index = False)

In [95]:
#trip_df.head()

In [96]:
#trip_df.count()

In [97]:
trip1_df.head()

,Unnamed: 0,Address,Description,FeatureCount,Fee,Langtitude,Latitude,MuseumName,PhoneNum,Rank,Rating
0,0,"555 Pennsylvania Ave NW, Washington DC, DC 200...",Find out for yourself why everyone is calling ...,3,Yes,-77.019235,38.893138,Newseum,+1 888-639-7386,8,4.5
1,1,"1000 5th Ave, New York City, NY 10028-0198",At New York City's most visited museum and att...,12,Yes,-73.962928,40.779166,The Metropolitan Museum of Art,1 212-535-7710,2,5.0
2,2,"945 Magazine Street, New Orleans, LA 70130-3813","Founded by historian and author, Stephen Ambro...",11,NaN,-90.070086,29.943004,The National WWII Museum,+1 504-528-1944,1,5.0
3,3,"2001 N Colorado Blvd, Denver, CO 80205-5798",The Denver Museum of Nature & Science is the R...,0,NaN,-104.941020,39.769189,Denver Museum of Nature & Science,303-370-6000,4,4.5
4,4,"111 S Michigan Ave, Chicago, IL 60603-6488","This Classical Renaissance structure, guarded ...",5,Yes,-87.623724,41.879547,Art Institute of Chicago,312 443 3600,1,5.0

In [104]:
## Rename Langtitude to Longitude
trip1_df = trip1_df.rename(columns={"Langtitude" : "Longitude"})
trip1_df.head()

,Unnamed: 0,Address,Description,FeatureCount,Fee,Longitude,Latitude,MuseumName,PhoneNum,Rank,Rating
0,0,"555 Pennsylvania Ave NW, Washington DC, DC 200...",Find out for yourself why everyone is calling ...,3,Yes,-77.019235,38.893138,Newseum,+1 888-639-7386,8,4.5
1,1,"1000 5th Ave, New York City, NY 10028-0198",At New York City's most visited museum and att...,12,Yes,-73.962928,40.779166,The Metropolitan Museum of Art,1 212-535-7710,2,5.0
2,2,"945 Magazine Street, New Orleans, LA 70130-3813","Founded by historian and author, Stephen Ambro...",11,NaN,-90.070086,29.943004,The National WWII Museum,+1 504-528-1944,1,5.0
3,3,"2001 N Colorado Blvd, Denver, CO 80205-5798",The Denver Museum of Nature & Science is the R...,0,NaN,-104.941020,39.769189,Denver Museum of Nature & Science,303-370-6000,4,4.5
4,4,"111 S Michigan Ave, Chicago, IL 60603-6488","This Classical Renaissance structure, guarded ...",5,Yes,-87.623724,41.879547,Art Institute of Chicago,312 443 3600,1,5.0

In [100]:
trip1_df.count()

Unnamed: 0      1014
Address         1014
Description      750
FeatureCount    1014
Fee               96
Langtitude      1008
Latitude        1008
MuseumName      1014
PhoneNum        1012
Rank            1014
Rating          1014
dtype: int64

In [101]:
#trip2_df.head()

In [102]:
#trip2_df.count()

In [105]:
trip1_path

'c:\\Users\\vaab2\\OneDrive\\Desktop\\Excercises in class\\Project-MAZE\\Valense\\Raw_Data\\tripadvisor_museum_USonly.csv'

In [107]:
trip1_df.to_csv(r'c:\\Users\\vaab2\OneDrive\\Desktop\\Excercises in class\\Project-MAZE\\Valense\\Raw_Data\\tripadvisor_final.csv', index = False)